"""
Конфигурация приложения
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "models"
LOGS_DIR = BASE_DIR / "logs"

DATA_DIR.mkdir(exist_ok=True)
MODELS_DIR.mkdir(exist_ok=True)
LOGS_DIR.mkdir(exist_ok=True)

API_TITLE = "Route Optimization API"
API_VERSION = "1.0.0"
API_DESCRIPTION = "API для оптимизации маршрутов с использованием Graph Neural Networks"

HOST = "0.0.0.0"
PORT = 8000
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

DATASET_PATH = DATA_DIR / "dataset.csv"
DEFAULT_MAX_POINTS = 10
DEFAULT_TRAFFIC_LEVEL = 3
DEFAULT_TRANSPORT_MODE = "car"
DEFAULT_OPTIMIZATION_METHOD = "genetic"

GNN_HIDDEN_DIM = 64
GNN_NUM_LAYERS = 3
GNN_DROPOUT = 0.1
GNN_NODE_FEATURES = 8

GENETIC_POPULATION_SIZE = 50
GENETIC_GENERATIONS = 100
GENETIC_CROSSOVER_RATE = 0.7
GENETIC_MUTATION_RATE = 0.1

CAR_SPEED_KMH = 50
WALK_SPEED_KMH = 5
TRAFFIC_FACTOR = 0.1  

DEFAULT_STOP_DURATION = 30 
WORK_START_DEFAULT = "09:00"
WORK_END_DEFAULT = "18:00"
LUNCH_START_DEFAULT = "13:00"
LUNCH_END_DEFAULT = "14:00"

MIN_POINTS = 2
MAX_POINTS = 100
MIN_STOP_DURATION = 1
MAX_STOP_DURATION = 300
MIN_TRAFFIC_LEVEL = 0
MAX_TRAFFIC_LEVEL = 10

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

CORS_ORIGINS = ["*"]
CORS_METHODS = ["*"]
CORS_HEADERS = ["*"]
CORS_CREDENTIALS = True
